#!/bin/bash
arm-none-eabi-size "${1}"

arm-none-eabi-objcopy -O ihex "${1}" "${1}.hex"

arm-none-eabi-objcopy -O binary "${1}" "${1}.bin"

cp "${1}" "${1}.elf"
arm-none-eabi-strip --strip-debug "${1}.elf"
arm-none-eabi-objdump -C -D "${1}.elf" > "${1}.S"